# Generated by Django 4.1.2 on 2024-07-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InnovateNow_Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonios',
            new_name='Testimonio',
        ),
    ]
