# Generated by Django 4.1.2 on 2024-07-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnovateNow_Web', '0002_rename_testimonios_testimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='imagen_testimonio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
